language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
install:
  - pip install -r requirements-${TRAVIS_PYTHON_VERSION}.txt.travis
script:   python setup.py test
notifications:
  irc: "irc.freenode.org##sparts"
