sudo: false
language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

before_install:
  - ./.travis-pre-install.sh

install:
  - ./.travis-install.sh

script:
  - python setup.py test

notifications:
  irc: "irc.freenode.org#sparts"
