language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

before_install:
  # Only prepare thrift stuff for python 2
  - if [ $(echo ${TRAVIS_PYTHON_VERSION} | cut -c1) = "2" ]; then

  # Prepare thrift for install
  - pushd externals/thrift
  - ./bootstrap.sh
  - ./configure

  # Compile the thrift compiler
  - echo "python " $(echo ${TRAVIS_PYTHON_VERSION} | cut -c1)
  - pushd compiler/cpp
  - make
  - popd

  # Compiler the python extension/modules, etc
  - pushd lib/py
  - python setup.py build
  - popd
  - popd
  - fi

install:
  - ./.travis-install.sh

script:
  - python setup.py test

notifications:
  irc: "irc.freenode.org#sparts"
